config/routes.rb
Rails.application.routes.draw do

  resources :books, only: [:index] do
    collection do
      get :data
      put :update_selected
    end
  end
  resources :authors, only: [:index]

  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates_uniqueness_of :name

  before_validation :normalize_name

  scope :with_normalized_name, -> (name){ where(name: Normalizer.normalize(name)) }

  private

    def normalize_name
      self.name = Normalizer.normalize(name)
    end
end

app/models/book.rb
class Book < ApplicationRecord
  paginates_per 100

  belongs_to :author

  acts_as_taggable_on :guessed_tags, :tags

  before_validation :set_author

  validates :asin, uniqueness: { scope: :tag }
  validates_presence_of :asin, :title

  def as_json(options={})
    attrs = {
      guessed_tag_list: guessed_tags.map(&:name).presence || [],
      tag_list: tags.map(&:name).presence || ['None'],
    }
    options.fetch(:tag_ids, []).each do |id|
      attrs["tag_list#{id}"] = tags.find{|e| e.id == id }.present? ? 'Y' : 'N'
    end
    super().merge(attrs)
  end

  private

    def set_author
      self.author = Author.with_normalized_name(self.raw_author).first_or_create!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.includes(:books).order(:name).all.select{|a| params[:books_count].present? ? (a.books.size >= params[:books_count].to_i) : true }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_tag_list

  def index
    @authors = Author.order(:name).all
    @total_books_count = Book.count
  end

  def data
    render json: Book.includes(:guessed_tags, :tags).order(date: :desc).limit(params[:limit]).offset(params[:offset]).to_json(tag_ids: @tag_list.map(&:id))
  end

  def update_selected
    books = Book.where(id: params[:book_ids]).all
    books.each do |book|
      if params[:type] == 'add_tag'
        book.tag_list.add(tag_to_update)
      elsif params[:type] == 'remove_tag'
        book.tag_list.remove(tag_to_update)
      end
      book.save!
    end
    redirect_back(fallback_location: books_path, notice: 'Updated')
  end

  private

    def load_tag_list
      @tag_list = ActsAsTaggableOn::Tagging.includes(:tag).where(context: :tags).map{|t| t.tag }.uniq.sort
    end

    def tag_to_update
      params[:tag_text].strip.presence || params[:tag_select].strip
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/authors/_filter.html.haml
.card
  .card-block
    = form_tag authors_path, class: 'form-inline', method: :get do
      .form-group
        = label_tag :books_count, 'Filter authors by books count'
        = select_tag :books_count, options_for_select([1,2,3,4,5,10,20,50].map{|v| [v,v] }, params[:books_count]), class: 'form-control'
      = submit_tag 'Filter', class: 'btn btn-default'

app/views/authors/index.html.haml
.row
  .col-md-12
    %h1 Authors
    = render 'filter'
    .row
      - @authors.in_groups_of((@authors.size/4.0).ceil, false) do |group|
        .col-md-3
          %ul
            - group.each do |author|
              %li= link_to "#{author.name} (#{author.books.size})", books_path(author_id: author.id, books_count: (params[:books_count].presence || 1))

app/views/books/_filter.html.haml
.card
  .card-block
    = form_tag search_books_path, class: 'form-inline', method: :get do
      .form-group
        = label_tag :books_count, 'Filter authors by books count'
        = select_tag :books_count, options_for_select([1,2,3,4,5,10,20,50].map{|v| [v,v] }, params[:books_count]), class: 'form-control'
      = submit_tag 'Filter', class: 'btn btn-default'

app/views/books/index.html.haml
.row
  .col-md-12
    %h1 Books
    .row
      .col
        .card
          .card-block
            .row
              .col-sm-4
                .row
                  .progress.col-sm-10.offset-sm-1.end
                    .progress-bar#stream_progress{style: "width: 0%;"} 0%
                %span#current_books_count 0
                %span#total_books_count{data: {count: @total_books_count}}= " / #{@total_books_count} Books found"
                .form-group
                  %label.sr-only{:for => "searchbox"} Search
                  %input#searchbox.form-control{:placeholder => "Search …", :type => "text"}/
                  %span.glyphicon.glyphicon-search.search-icon
                .form-group
                  = select_tag :author, options_for_select([['Author', 'all']] + @authors.map{|a| [a.name, a.id] }), class: 'form-control'
                .form-group
                  = submit_tag 'Clear', class: 'btn btn-secondary btn-default', id: 'clear_filter_button'
              #tag_list.col-sm-8.end
                %h5 Filter by Tag list
                - @tag_list.each do |tag|
                  .form-check{id: "tag_list#{tag.id}", style: 'margin-bottom: 0;'}
                    = label_tag "tag_list_label#{tag.id}", "#{tag.name} (#{tag.taggings_count})", style: 'margin-bottom: 0;'
                    %label.form-check-label
                      %input.yes{:type => "checkbox", :value => 'Y'} Y
                    %label.form-check-label
                      %input.no{:type => "checkbox", :value => "N"} N

    = form_tag update_selected_books_path, method: :put, class: 'form-horizontal' do
      .row
        .col
          .card
            .card-block
              .row
                .col-sm-12.form-inline
                  .row
                    .col-sm-12
                      = select_tag :tag_select, options_for_select(@tag_list.map(&:name)), include_blank: true, class: 'form-control'
                      = text_field_tag :tag_text, nil, class: 'form-control', placeholder: 'Tag'
                      = submit_tag 'Add', formaction: update_selected_books_path(type: :add_tag), class: 'btn btn-primary btn-sm'
                      = submit_tag 'Remove', formaction: update_selected_books_path(type: :remove_tag), class: 'btn btn-primary btn-sm'
      .row
        .col
          = render 'book_row'
          %table#books.table.table-striped.table-hover.table-sm
            %thead
              %tr
                %th= check_box_tag "select_all", nil, false, class: 'select_all'
                %th Title
                %th Author
                %th Date
                %th Guessed Tags
                %th Tags
            %tbody#books-body

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_flash_class(type)}" }
    = message
    %button.close{ data: { dismiss: 'alert' } } x

app/views/layouts/_navigation.html.haml
%nav.navbar.sticky-top.navbar-toggleable-md.navbar-inverse.bg-warning
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{:href => root_path} 積読
  #navbarNavAltMarkup.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item{class: (params["controller"] == "books" ? 'active' : nil)}
        %a.nav-link{:href => books_path} Books
      %li.nav-item{class: (params["controller"] == "authors" ? 'active' : nil)}
        %a.nav-link{:href => authors_path} Authors

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 積読
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .container-fluid
      = yield